#!/usr/bin/env python3
"""Regenerate the gzipped web page headers for examples/PRINTER_FW.

Edit index.html / image.html, then run:  python3 tools/html_to_header.py
The pages are served with Content-Encoding: gzip, which cuts their flash use ~5x.
"""
import gzip
import os

SKETCH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "examples", "PRINTER_FW")

PAGES = [
    ("index.html", "ATOM_PRINTER_HTML.h", "printer_html", "_ATOM_PRINTER_HTML_H"),
    ("image.html", "ATOM_IMAGE_HTML.h", "image_html", "_ATOM_IMAGE_HTML_H"),
]

for source, header, name, guard in PAGES:
    with open(os.path.join(SKETCH, source), "rb") as f:
        html = f.read()
    # mtime=0 keeps the output identical between runs
    data = gzip.compress(html, compresslevel=9, mtime=0)
    rows = [
        "    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ","
        for i in range(0, len(data), 16)
    ]
    with open(os.path.join(SKETCH, header), "w", newline="\n") as f:
        f.write(f"// Generated by tools/html_to_header.py from {source}; do not edit by hand.\n")
        f.write(f"// gzip-compressed, {len(html)} bytes uncompressed.\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n#include <Arduino.h>\n\n")
        f.write(f"const uint8_t {name}[] PROGMEM = {{\n")
        f.write("\n".join(rows) + "\n};\n\n#endif\n")
    print(f"{source}: {len(html)} -> {len(data)} bytes ({header})")
